Update the way selecting a future date for schedulePost
Automattic/Edit-Flow pull request #665
Opened 2021-06-09 10:46 UTC by htdat

Fix #652 

## Description

The root cause is described here https://github.com/Automattic/Edit-Flow/issues/652#issuecomment-857577431

To fix this issue, I am changing the way selecting a future date for schedulePost: 

- Calculate the date in 2 weeks since today. 
- Use DOM selector and update the respective values for day, month, year. 

## Steps to Test

- Check out this PR.
- Run E2E tests and verify the issue in #652 is no longer.

If possible, we can use the diff in this comment https://github.com/Automattic/Edit-Flow/issues/652#issuecomment-857577431 to generate new screenshots with this fix.

With this fix, the date of the post is expected now: 

- [schedulePost_before-choosing-date](https://user-images.githubusercontent.com/10045087/121340563-f8450300-c949-11eb-8983-14c31b5886fd.png): date is today - June 09. 
- [schedulePost_after-choosing-date](https://user-images.githubusercontent.com/10045087/121340567-f9763000-c949-11eb-837b-a230b4a7cd87.png): date is the date after 14 days: June 23. 
- [calendar_before-drag-drop](https://user-images.githubusercontent.com/10045087/121340571-fa0ec680-c949-11eb-8095-869f47c7cdbd.png): date is show the expected scheduled post date: June 23 
- [calendar_after-drag-drop](https://user-images.githubusercontent.com/10045087/121340573-faa75d00-c949-11eb-9890-3175e94ceef6.png): after the drag and drop, it is moved up to June 16.

2021-06-10 06:51 UTC, htdat commented
In case, it help, here is my screen record for the specific failed test with this fix: 

https://d.pr/v/kWnVMx

2021-06-10 13:28 UTC, nielslange submitted a review, later dismissed
LGTM!

I tested this PR using the following steps:

1. Start Docker
2. Run `npm run wp-env start`
3. Run `npm run test-e2e`
4. One test case is failing
```
> edit-flow@2.0.0 test-e2e
> wp-scripts test-e2e --config tests/e2e/jest.config.js

 FAIL  tests/e2e/specs/calendar-body.test.js (25.717s)
  ● Calendar Body › expects a scheduled post can be dragged and dropped

    expect(received).not.toContain(expected) // indexOf

    Expected value: not "Scheduled Post"
    Received array:     ["Scheduled Post", "Published Post"]

      94 |         expect(await scheduledPostDay.evaluate((node) => {
      95 |             return Array.prototype.slice.call(node.querySelectorAll('.item-headline.post-title strong')).map((n) => n.innerText)
    > 96 |         })).not.toContain('Scheduled Post');
         |                 ^
      97 |     });
      98 | });

      at _callee3$ (specs/calendar-body.test.js:96:17)
      at asyncGeneratorStep (specs/calendar-body.test.js:7:103)
      at _next (specs/calendar-body.test.js:9:194)
          at runMicrotasks (<anonymous>)
      at processTicksAndRejections (../../node:internal/process/task_queues:96:5)

 PASS  tests/e2e/specs/editorial-comments.test.js (7.023s)
 PASS  tests/e2e/specs/calendar-header.test.js (5.558s)
 PASS  tests/e2e/specs/simple.test.js

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        39.61s, estimated 40s
Ran all test suites.
```
5. Check out this PR
6. Run `npm run test-e2e`
7. All test cases are successful
```
> edit-flow@2.0.0 test-e2e
> wp-scripts test-e2e --config tests/e2e/jest.config.js

 PASS  tests/e2e/specs/calendar-body.test.js (25.829s)
 PASS  tests/e2e/specs/calendar-header.test.js (5.989s)
 PASS  tests/e2e/specs/simple.test.js
 PASS  tests/e2e/specs/editorial-comments.test.js (6.472s)

Test Suites: 4 passed, 4 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        39.641s
Ran all test suites.
```

2021-06-11 19:13 UTC, mikeyarce requested changes
Looks good to me!  I just had a small nitpick about one of the comments.

Thanks @htdat - so nice to see that green checkmark next to all the tests!

2021-06-14 03:57 UTC, merged

2021-06-14 03:59 UTC, htdat commented
Thanks @nielslange and @mikeyarce! I've merged this PR.