Add fixes for PHP 8.2
Automattic/Edit-Flow pull request #699
Opened 2023-09-05 19:43 UTC by srtfisher

Add fixes for PHP 8.2 dynamic properties.

2023-09-06 20:14 UTC, EAGLESWhit commented
Please review this soon. WPEngine is having everyone go to PHP 8.2 at the end of October.

"WP Engine’s PHP 8.0 will be reaching end of life on October 31. Prepare your websites for the PHP 8.2 upgrade to experience increased security and performance." - WPEngine

2023-10-03 19:10 UTC, rebeccahum requested changes

2023-10-03 19:10 UTC, rebeccahum commented on common/php/class-module.php
> +#[\AllowDynamicProperties]
Is this attribute necessary since I see that the properties are later being defined?

2023-10-03 19:10 UTC, rebeccahum commented on edit_flow.php
> +#[\AllowDynamicProperties]
Same as above ^^.

2023-10-04 19:07 UTC, rebeccahum commented
Closing in favour of #700

2023-10-04 19:07 UTC, closed without merging